import { StrictMode } from 'react' /* Importamos el componente StrictMode de React para envolver nuestra aplicación y activar verificaciones adicionales durante el desarrollo, lo que ayuda a identificar problemas potenciales en la aplicación y mejorar la calidad del código. Esto es especialmente útil para detectar problemas relacionados con el ciclo de vida de los componentes, advertencias sobre prácticas obsoletas y otros problemas comunes que pueden surgir durante el desarrollo de una aplicación React. Al utilizar StrictMode, podemos asegurarnos de que nuestra aplicación siga las mejores prácticas y sea más robusta y fácil de mantener a largo plazo. */
import { createRoot } from 'react-dom/client' /* Importamos la función createRoot del paquete react-dom/client para crear un punto de entrada para renderizar nuestra aplicación React en el DOM. Esta función es parte de la nueva API de renderizado introducida en React 18, que permite una mejor gestión del rendimiento y la concurrencia en las aplicaciones React. Al utilizar createRoot, podemos aprovechar las mejoras en el rendimiento y la capacidad de respuesta de nuestra aplicación, lo que es especialmente importante para aplicaciones interactivas como esta selección de Pokémon, donde la experiencia del usuario es clave. */
import './index.css' /* Importamos el archivo de estilos index.css para aplicar estilos globales a nuestra aplicación. Este archivo puede contener estilos personalizados, así como la importación de bibliotecas de estilos como Tailwind CSS, que se utiliza en esta aplicación para facilitar la creación de una interfaz de usuario atractiva y responsiva. Al importar este archivo, aseguramos que los estilos definidos en él estén disponibles en toda la aplicación, lo que nos permite mantener un diseño coherente y mejorar la experiencia visual del usuario. */
import App from './App.jsx' /* Importamos el componente principal App.jsx, que es el punto de entrada de nuestra aplicación React. Este componente contiene la lógica principal de la aplicación, incluyendo la gestión del estado, la interacción del usuario y la renderización de los diferentes componentes que conforman la interfaz de usuario. Al importar App.jsx, podemos renderizar este componente en el DOM utilizando createRoot, lo que permite que nuestra aplicación se muestre en la pantalla del usuario y funcione correctamente. El componente App.jsx es esencial para la estructura y funcionalidad de nuestra aplicación de selección de Pokémon, ya que coordina todos los aspectos de la experiencia del usuario y la lógica del juego. */

createRoot(document.getElementById('root')).render( // Utilizamos createRoot para crear un punto de entrada en el DOM donde se renderizará nuestra aplicación React. En este caso, seleccionamos el elemento con el id 'root' como el contenedor principal para nuestra aplicación. Luego, llamamos al método render para renderizar el componente App dentro de StrictMode, lo que activa las verificaciones adicionales durante el desarrollo y mejora la calidad del código. Esto es esencial para garantizar que nuestra aplicación funcione correctamente y proporcione una experiencia de usuario óptima al seleccionar Pokémon y navegar por la interfaz. */
  <StrictMode> {/* Envolvemos el componente App dentro de StrictMode para activar las verificaciones adicionales durante el desarrollo, lo que ayuda a identificar problemas potenciales en la aplicación y mejorar la calidad del código. Esto es especialmente útil para detectar problemas relacionados con el ciclo de vida de los componentes, advertencias sobre prácticas obsoletas y otros problemas comunes que pueden surgir durante el desarrollo de una aplicación React. Al utilizar StrictMode, podemos asegurarnos de que nuestra aplicación siga las mejores prácticas y sea más robusta y fácil de mantener a largo plazo. */}
    <App /> {/* Renderizamos el componente App, que es el punto de entrada de nuestra aplicación React. Este componente contiene la lógica principal de la aplicación, incluyendo la gestión del estado, la interacción del usuario y la renderización de los diferentes componentes que conforman la interfaz de usuario. Al renderizar App dentro de StrictMode, podemos aprovechar las verificaciones adicionales para mejorar la calidad del código y garantizar que nuestra aplicación funcione correctamente, proporcionando una experiencia de usuario óptima al seleccionar Pokémon y navegar por la interfaz. */}
  </StrictMode>, // Cierre del componente StrictMode
)
